### ISSUE TITLE
Compilation from archive: fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by juju4** [csirtgadgets/massive-octo-spice#169]
I'm trying to build cif on macports (https://trac.macports.org/ticket/43011).

If I do the build from git cloning, it's working ok.
if doing by retrieving archive, it fails with above error.
Macports system prefers source archives instead of git/svn/cvs.

Thanks

**Comment by wesyoung** [comment]
i think to solve this we just need to create an archive that contains a prep'd configure.ac and makefile?

right now the easybutton does a "bash autogen.sh" for you, that sets up the configure.ac and makefiles, in the alpha's we haven't done much in terms of hosting "ready to go sources", just because we're updating the master so much.

i did a quick `make dist` on the master branch and appended it to alpha.16:

https://github.com/csirtgadgets/massive-octo-spice/releases/download/2.00.00-alpha.16/cif-2.00.00-alpha.16-1-gd6a05f3.tar.gz

lmk if that gets you closer....

**Comment by wesyoung** [comment]
https://github.com/csirtgadgets/massive-octo-spice/releases/tag/2.00.00-alpha.16
