### ISSUE TITLE
test group permissions

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/massive-octo-spice#230]
test with different tokens, that have different groups, make sure each token can only view the data it should be able to.

this might get a little funky with searches, see #228

**Comment by giovino** [comment]
searches and feeds

**Comment by giovino** [comment]
I was able to test the following observables added under group01 were not visable to a user in the 'everyone' group:

* fqdn
* url
* ipv4
* email address
* hash

I was not able to test ipv6 due to this issue (https://github.com/csirtgadgets/p5-cif-sdk/issues/32)

Still need to test/verify:

1. if a post-processed domain from a URL is re-injected with the proper group permission
2. feeds and groups are working as expected

**Comment by giovino** [comment]
This script can be used for testing of permissions. 

https://github.com/csirtgadgets/massive-octo-spice/blob/develop/contrib/group_testing.sh

**Comment by wesyoung** [comment]
so are we done here?

**Comment by giovino** [comment]
I suggest we leave this open until these two get addressed:

https://github.com/csirtgadgets/p5-cif-sdk/issues/35
https://github.com/csirtgadgets/p5-cif-sdk/issues/36

e.g. the script runs without errors.

**Comment by giovino** [comment]
I tested the group_testing.sh script against beta-09 today and it returned zero errors, assuming the logic is sound, I think we are good. We should run the testing script before we launch for regression testing.
