### ISSUE TITLE
Out put file location or process of giving out put

### ISSUE THREAD

**Issue by diveshshah** [csirtgadgets/massive-octo-spice#439]
Hi,

I am new to CIF server .
can u please share where CIF server store ip  and URL data files from connected sites ?
or 
Is CIF server check online to those sites about required query.?

Why for any Small Instance required.
at-least 16GB ram
at-least 8 cores

Thanks
Divesh Shah

**Comment by wesyoung** [comment]
i'm not sure i understand the question? the data is stored in an embedded elasticsearch instance. see:

https://github.com/csirtgadgets/massive-octo-spice/wiki/The-CIF-Book

a small instance requires that kind of hardware because of all the post processing of the data that takes place (ie: urls --> fqdn's --> ip address). CIF takes lots of urls and domains and tries to resolve them [multi-threaded] into their respective parts (ip addresses, etc).
