### ISSUE TITLE
Problems with installation on Ubuntu 14 LTS

### ISSUE THREAD

**Issue by schizophrenchen** [csirtgadgets/massive-octo-spice#474]
Hi all,
i encountered some problems when installing "massive-octo-spice" from the most current repo (downloaded the ZIP from https://github.com/csirtgadgets/massive-octo-spice - version from march/02/2017) by running the easybutton_curl.sh.
The error is related to ubuntu.sh, when it tries to install a certain perl module via CPAN. Compare line 65 of ubuntu.sh under <unzip-dir>/hacking/platforms/ubuntu/ubuntu.sh.

The line causing the issues on my side was "cpanm ZMQ::FFI@0.17" (#65). After the installer broke, i was adviced to add "--force" to the line. So i patched "cpanm ZMQ::FFI@0.17" to ""cpanm --force ZMQ::FFI@0.17" and the installation worked like a charm.

I have no idea what this module is for or what dependency makes the installation crash, but the force switch did the job.

Just wanted to let you know, if you struggle with the same thing.
Maybe (if still "supported") you can patch that?

Thanks,
Markus

**Comment by wesyoung** [comment]
hrm. something else funny may be going on (since i literally cut and installed .08 yesterday). i'll take a look.. TY!

(ps: in the future you should be using the release tags for this and v3, not the main repo.. sometimes things get funny that way..)

https://github.com/csirtgadgets/massive-octo-spice/releases/tag/2.00.08

**Comment by schizophrenchen** [comment]
Sure i will. Thanks for your awesome and quick responses and fixes!
Markus

**Comment by schizophrenchen** [comment]
So just installed massive-octo-spice-2.00.08 successfully on Ubuntu 14 LTS without any hacks/patches...

**Comment by wesyoung** [comment]
good deal. in v3 we're gonna do a little more to try and "block" you from trying to install from master unless you really know what you're doing. have had a lot of experiences like this, moving to ansible as the build system has helped some of this (instead of using bash scripts). but there's still a lot more we're planning to do to make this a little less confusing...

ty for testing that, much appreciated. :)
